### PR TITLE
Add option to initialize enabled

### PR DESCRIPTION
**Pull request by kassio**
Hi there! First of all thanks for the great App!

One thing that I miss, is the option to launch it in the login already active in the last active session. So, I'd propose to add an option like:

image

What do you think?

_Swift is not my main language, I'm sorry if I mess too much with the code._

### CODE REVIEW

**Comment by lvillani** [comment]
Is this intended to remember Chai's enabled state between sessions (and whether it was enabled for e.g. 2 hours)?

**Comment by kassio** [comment]
@lvillani, yes, the original intent was to remember Chai's enabled state between sessions when the user restart the computer between sessions. 

If the last session was for two hours, it should restart with a new 2hours session. Reading the question, though, I'm not sure the changed code will do that. 😬

**Comment by lvillani** [comment]
Got it! Would you mind if I merge your changes one at a time (with attribution) instead of merging this PR directly? The `ActivationSpec` refactor looks good and I would like to bring it in as a separate commit 🙂

**Comment by kassio** [comment]
@lvillani no problem at all. 😄 I'm glad to help.

**Pull request closed without merging**
